print("To run the toy experiments:")

print("1) Baseline:")
print("   python scripts/run_toy_baseline.py")
print()
print("2) VIREON controller:")
print("   python scripts/run_toy_vireon.py")
print()
print("3) Aggregate stats over many seeds:")
print("   python scripts/run_toy_stats.py")
print()
print("Outputs:")
print("- Console summary of node counts and best values")
print("- CSV at results/toy_stats.csv for deeper analysis")
